### ISSUE TITLE
OpenCV 3.0.0 and enqueueMemSet

### ISSUE THREAD

**Issue by alexanderkoumis** [anuranbaka/OpenDTAM#24]
Hello, I have attempted to upgrade OpenDTAM to OpenCV 3.0.0. Please see the following branch for relevant code:

https://github.com/alexanderkoumis/OpenDTAM

I have made the modifications necessary in order for it to run. However, It will run through maybe one set, freeze after the CostVolume destructor, and restart, not showing good depth images in the preview windows (I have run the system on 2.4 and seen the correct behavior). I believe it has something to do with taking out "enqueueMemSet" from the CostVolume constructor on lines 88 and 80 [here](https://github.com/alexanderkoumis/OpenDTAM/blob/3.0.0/Cpp/CostVolume/CostVolume.cpp):

```cpp
//    cvStream.enqueueMemSet(loInd,0.0);
//    cvStream.enqueueMemSet(dataContainer,initialCost);
```

Not too familiar with the new OpenCV CUDA API so I am not sure if this is the faulty area. Any thoughts?

Thanks,
Alexander

**Comment by anuranbaka** [comment]
I believe this is because the container values need to be initialized. enqueueMemSet was removed from opencv 3.0. You can use "loInd.setTo(Scalar(0, 0, 0),cvStream)" and "dataContainer.setTo(Scalar(initialCost),cvStream)" to do the same I believe

If that works please send a pull request with the change.
-Paul

**Comment by alexanderkoumis** [comment]
Hi Paul,
Should I work on the master or experimental? I noticed master has been written for 3.0.0 support (though I could not get it to run). I could either send a request for my separate branch (which is based on 2.4.9 experimental) or try to improve the master and integrate changes made to experimental in the 12 or so commits it is ahead. 

Alexander

**Comment by anuranbaka** [comment]
Well I'm spending the day trying to get the repo into a vaguely sane state... my own repo is getting several commits ahead as well. The fix should be in the master branch, since that is supposed to work on OpenCV 3, although it was a pre alpha build, so it may not work anymore.

That fix will slow down builds for 2.4.9 because the optimization was not included in the setTo function.

I'm going to push the experimental origin as far forward as I can today and pull in some changes from avindra's ptam fork.

**Comment by anuranbaka** [comment]
Done, had to force a push to overwrite a Readme change that was messing up the history

**Comment by alexanderkoumis** [comment]
I could not build with latest changes to `CostVolume.cpp` made in experimental, originShift is undefined:

![originshift](https://cloud.githubusercontent.com/assets/5108856/7082233/6e6ea328-df05-11e4-97be-d893390f94c6.png)

**Comment by anuranbaka** [comment]
I'm wondering if this worked?

**Comment by alexanderkoumis** [comment]
Yes, changes made in the following commit fixed error:

https://github.com/alexanderkoumis/OpenDTAM/commit/95560e589c71cb7a57c20b7d0108e74d8e51d7e8

Will try to send a cleaner 3.0.0 pull request soon

**Comment by anuranbaka** [comment]
Oh my, didn't realize that was still outstanding. Thanks for following up!
