### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by subokita** [anuranbaka/OpenDTAM#48]
I'm sorry, but what's the license of OpenDTAM again?

**Comment by anuranbaka** [comment]
"// Free for non-commercial, non-military, and non-critical
// use unless incorporated in OpenCV.
// Inherits OpenCV Licence if in OpenCV."
Since the denoising core got pulled into OpenCV, you can consider any of the DepthMapDenoiseWeightedHuber directory and the CostVolume directory to be BSD

The Track folder and root were not pulled into OpenCV, so they are effectively CC BY-NC with military use excluded.
